name: Build Instant Eyedropper Tool

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild instanteyedropper.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: path_to_your_build_output/*.exe
